### PR TITLE
Removes 1 honor hack

### PR DESCRIPTION
**Pull request by Slivo-fr**
This is the second step to remove the 1 honor hack for player that does 15hk on day one.

The #217 makes it possible, we should wait for a while before merging this one, let's say at next com bump or in 6+ months so most players are up to date.

DO NOT MERGE YET

### CODE REVIEW

**Comment by Slivo-fr** [comment]
~~Nevermind, this would cause some side effects due to blizzard incapacity to reset properly~~

**Comment by teelolws** [comment]
Can you bump the TOC Interface for the new patch? I cbf.

**Comment by Slivo-fr** [comment]
This shouldn't be merged for a while so I'd say this isn't the best place to do it

**Comment by Slivo-fr** [comment]
We should be fine with merging this now @kakysha :D

**Pull request merged**
