### PR TITLE
Adds compression, encoding and length check on comms messages

### LINKED ISSUE #142: Massive Amounts of Player Duplicates This Week
Starting just this week, honorspy has been creating massive amounts of duplicates of players. In the past, there was only a few here and there, but this week it seems that every single player on my list has 2 or 3 people who show as the exact same RP/Honor/Last Weeks Honor/etc. 

I have even found one person who is being shown as a "duplicate" (as in, they have way less honor/RP as shown in the honorspy table. Upon inspecting this persons honor tab manually, the Honorspy table updated with the correct version. 

This is really concerning still, however. With the number of duplicates on the table, it makes me wonder if the pool size is correct or not. Many of these "duplicated" players likely don't have 15 HK's for the week, and thus the pool size may be massively inflated in a false manner. Unless these players log back in/get inspected by someone else, they don't update correctly. This has massive implications for bracket stacking based on estimated pool sizes and has the rankers on my server in near panic-mode this week. 

I've attached an example image of the massive number of duplicates. 
WoWScrnShot_053020_231308

### LINKED ISSUE #198: Honorspy is sometime mixing up character data
On some undefined edge cases, Honorspy stores data from a first char to another one, including it's class.
On the example below, Elerina is a rogue and has been given Edens ranking data (Last week honor, standing, etc)

image

### PR DESCRIPTION
**Pull request by Slivo-fr**
Fix #198 
Fix #142 

~~Here is a first draft, feel free to review~~

### CODE REVIEW

**Comment by teelolws** [comment]
if (HonorSpyUtils:getCompleteName(sender) == playerName) then return end

Make sure that works on realms with spaces in the name.

**Comment by teelolws** [comment]
Other than that (and the debugging prints), it all looks good to me. We hopped on the PTR and tested it, seems to work well.

**Comment by Slivo-fr** [comment]
> Make sure that works on realms with spaces in the name.

Tested, does works !

**Comment by Slivo-fr** [comment]
I'm done with everything I was working on.
You may release a new version once we rejected/merged open merge requests

**Pull request merged**
