### PR TITLE
Add check and timer for ongoing inspection

### PR DESCRIPTION
**Pull request by Slivo-fr**
In order to try to solve #198 

This is a draft to discuss. Please do not merge it needs further testing.

### CODE REVIEW

**Comment by teelolws** [comment]
Nah cause if the inspect fails and inspect data is never received, the addon will be stuck never inspecting anyone else until the next reload.

**Comment by Slivo-fr** [comment]
Negative, because of the last_inspect_time check, we start again after 1s if the event doesn't fire
(It wasn't properly implemented before my last push)

**Comment by kakysha** [comment]
fix formatting a bit with obsolete newlines etc.

**Comment by Slivo-fr** [comment]
I'm not sure why spacing is fucked up, aren't we using LF ?

It's fine on my end, see 
image

**Comment by Slivo-fr** [comment]
There, I may have a tab/spacing issue with my IDE

**Comment by teelolws** [comment]
I think he means make it more like

`
        if (

			paused or

			(not C_PlayerInfo.UnitIsSameServer(PlayerLocation:CreateFromUnit(unitID))) or

			currentlyInspecting or

                        ((GetTime() - lastInspectTime) < 1)

        ) then
`

**Comment by Slivo-fr** [comment]
@teelolws this snippets is outdated, I've updated the implementation since then (I forced push, check https://github.com/kakysha/HonorSpy/pull/201/files)

**Comment by teelolws** [comment]
My post is still relevant to that.

**Comment by Slivo-fr** [comment]
We discussed it on discord, all good

**Pull request closed without merging**
