### PR TITLE
Cross faction

### PR DESCRIPTION
**Pull request by DBFBlackbull**
On many smaller private servers, cross faction grouping is allowed. This pollutes the data with alliance players, making it harder to see the current standings.

This fix ensures that inspects does not add alliance players to the horde tables and vice versa.

`UnitRace()` was used instead of `UnitFactionGroup()` as cross realm servers places all players into the same faction while grouped.

### CODE REVIEW

**Review by kakysha — APPROVED** [review]
Great Job! Thank you @DBFBlackbull

**Comment by DBFBlackbull** [comment]
Thank you for merging this. Now I don't have to fork your repo anymore.
I was thinking of adding Horde and Alliance to The DB so that you can track both sides if you have a character in each faction on the same server

**Comment by kakysha** [comment]
I don't remember where the addon is storing the state, on a per-realm SharedVariables or per-character, so your addition will only work if it's stored on a per-realm basis.
BTW, how does UI perform on a vanilla version on modern private servers population? I remember it had hard times generating a table with more than 500 players in it, 1k+ was unbearable

**Comment by DBFBlackbull** [comment]
Well the private server I am playing on, only have like 10-15 people in total playing on both sides so it has not been a problem for me.

As for the saved data it is already saved per-realm so it should be an easy fix to add a faction dimention to the table to track both sides. Now for a UI to switch between the two is another story, I don't really want to do that :)

**Pull request merged**
