### PR TITLE
Use full name-server string for stored player, even from same servers

### PR DESCRIPTION
**Pull request by Slivo-fr**
In order to make HS data more consistent over connected servers and logic more simple, mostly on coms.
May also solve / help simplify debug for the two duplicate/other server player issues we are dealing with.

I also removed the uft8.lower calls to avoid the reported crash from curse. (https://www.curseforge.com/wow/addons/honorspy?comment=434)

As playername won't be the same and sync works differently, I bumped the com prefix again

### CODE REVIEW

**Comment by Slivo-fr** [comment]
I will be testing this on my ERA cluster for the next week.

**Comment by Slivo-fr** [comment]
I've also included  a small change to the GUI display, so player without estimated honor values will have empty estHonor columns again. It will be easier to see who uses the addon or not.

**Comment by Slivo-fr** [comment]
Does seems to fix #184, maybe even #175

**Comment by teelolws** [comment]
Tested and looks good. I support this PR.

**Comment by Slivo-fr** [comment]
We just found out one issue, fixing in progress, will require a bit more testing afterward !

**Comment by teelolws** [comment]
Yup that fixed the issue I had. PR supported.

**Comment by Slivo-fr** [comment]
Oh, I was planning some more testing now that the incoming broadcast is fixed !
Do you want to release it as it is to see how it goes live ?

**Comment by kakysha** [comment]
I should have left it as draft so you convert it to PR when ready? I've never seen draft PRs before :) ok then, test it and in case no errors, just poke me here and I'll release.

**Comment by Slivo-fr** [comment]
Yeah I was going to set it ready for review when testing was done !
I will do the testing and message here to let you know you can release if I don't find any issue

**Comment by Slivo-fr** [comment]
Sounds good to me. I think you may release an update tomorrow if you can.

**Comment by Slivo-fr** [comment]
Is there anything wrong preventing release ?

**Comment by kakysha** [comment]
oh, sorry, I just forgot...
On your side, you also forgot to bump version in TOC :)

**Comment by Slivo-fr** [comment]
No worries, I was just wondering !
Well about the toc I don't feel like deciding when to bump / release on your behalf !
If you ask me to, I'll certainly do it however :D

**Pull request merged**
