### PR TITLE
Add pool command option

### PR DESCRIPTION
**Pull request by Slivo-fr**
image

### CODE REVIEW

**Comment by Slivo-fr** [comment]
Hold on the merge button for a second please :D

**Comment by Slivo-fr** [comment]
Now it's ready!

**Comment by kakysha** [comment]
conflicts :(

**Comment by Slivo-fr** [comment]
I will rebase tomorrow, classic locale merging :P

**Comment by kakysha** [comment]
Also please bump addon version in .TOC file too so I can release the new version.

**Comment by Slivo-fr** [comment]
Here we go !

**Comment by Slivo-fr** [comment]
image
Hmmm should it be 1.8.2 ? Do I bump to 1.8.4 ?

**Comment by teelolws** [comment]
Bump to 1.8.5 cause I'm about to push a 1.8.4

**Comment by Slivo-fr** [comment]
Copy !

**Pull request merged**
