### PR TITLE
Factorize the player broadcast code

### PR DESCRIPTION
**Pull request by Slivo-fr**
Fix the hourly broadcast error with non existing `HonorSpy:broadcastPlayers` function

### CODE REVIEW

**Comment by teelolws** [comment]
~~Whatever you changed is causing an error for me:~~

**Comment by Slivo-fr** [comment]
I'm taking a look, thanks !

**Comment by teelolws** [comment]
Nvm its cause I didn't copy over the Localization folder.

**Comment by Slivo-fr** [comment]
Cool, you scared me :D
Thanks for reporting anyway, always better to double check just in case !

**Pull request merged**
