### PR TITLE
Fix GUI honor values

### LINKED ISSUE #171: Issue with latest release - column values
I think your formula is a bit awry on the latest update pushed yesterday.  The EstTodayHonor column contains a value that is adding what you actually got today to the known honour.  Thus when it calculates for EstWeekHonor it looks like you have twice as much as you do have.

### PR DESCRIPTION
**Pull request by Slivo-fr**
Fixes #171 

Also adds a toggle setting for estTodayHonor and fix sorting

### CODE REVIEW

**Comment by teelolws** [comment]
You should merge this into your other fork first, then ~~PR it here.~~ just let it join the PR for your other fork.

**Comment by Slivo-fr** [comment]
I found an issue, working on it, do not merge yet !

**Comment by Slivo-fr** [comment]
There, added a check to prevent a lua error.
Let me test this properly, I'll leave a message when it's done

**Comment by Slivo-fr** [comment]
We should be fine now :)

**Comment by teelolws** [comment]
Since I can't do a PR into your fork, heres fixes to sorting, and also the "EstWeekHonor" column was showing the wrong number:
[honorspy.zip](https://github.com/kakysha/HonorSpy/files/8227052/honorspy.zip)

**Comment by Slivo-fr** [comment]
I've added the bit related to the GUI change I made, I don't feel comfortable to push the other changes.
Could you please open a separate PR for the sorting part? It would be easier to review

**Comment by teelolws** [comment]
If I make a PR it will create conflicts that I can't resolve during the hours you can.

**Comment by Slivo-fr** [comment]
Why would it ? I didn't alter the code you are modifying for sorting

**Comment by teelolws** [comment]
wtf is going on with this diff? It says the entire file changed? https://github.com/Slivo-fr/HonorSpy/commit/0459a1a635a6ec2a07b939a1a20983a1572e7131

**Comment by Slivo-fr** [comment]
Indeed, it looks like there is some spacing issues, I will fix that tomorrow

**Comment by teelolws** [comment]
Eh leave it. But here is the diff with ignore-whitespace-changes:
image

**Comment by Slivo-fr** [comment]
@kakysha any chance to get this reviewed / merged / released with the com bump so we can monitor if the #175 is fixed please ?

**Comment by Slivo-fr** [comment]
Thanks a lot :)

**Pull request merged**
