### PR TITLE
Update translations for SoM and fix decay factor for SoM ranking estimate

### PR DESCRIPTION
**Pull request by Aleks1015**
-Updated all translation files for Season of Mastery update

-Added esES and esMX translations and added Season of Mastery changes from 3 open pull requests into this update.

-Fixed decay issue causing higher rank estimates in Season of Mastery

### CODE REVIEW

**Comment by Aleks1015** [comment]
Pull request files for 2 translation files (requests 148,149 and 150) have been included.  I believe those can be closed if this is integrated.

**Comment by Aleks1015** [comment]
Fixed issue where decay factor needs to be adjusted for SoM.  Decay factor will be correct when calculating for Season of Mastery

**Comment by Aleks1015** [comment]
Corrected 'Swamp of Sorrows (AU)' SoM realm check

**Comment by Aleks1015** [comment]
Checked reported lua errors, localization files resolved those.  Restored previous roll back to apply to SoM - not producing any errors now and the spam has stopped.  No further changes to this revision planned pending feedback

**Comment by kakysha** [comment]
Good work, thanx again!

**Comment by Aleks1015** [comment]
Thanks!

 

I had to apply the fix you reverted again but found exactly why the online friend spam is occurring after that and tagged it.  Created another pull for this.

**Pull request merged**
